#!/bin/bash
counter=1
while [ $counter -le 100 ]
do
        if [ $(($counter % 2)) == 0 ]
        then
                echo "Even number" $counter
        fi
((counter++))
done

counter=1
while [ $counter -le 100 ]
do
        if [ $(($counter % 2)) == 1 ]
        then
                echo "Odd Number is" $counter
        fi
((counter++))
done


counter=1
while [ $counter -le 100 ]
do
        if [ $(($counter % 5)) == 0 ]
        then
                echo "Number is divided by 5" $counter
        fi
((counter++))
done


